version: "3.7"
services:
    dkr-eclim:
        build: .
        user: eclim
        #volumes:
            #- '~/.vim/eclim:/home/eclim/.vim/eclim'
            #- '~/.vim/plugin/eclim.vim:/home/eclim/.vim/plugin/eclim.vim'
        ports:
            - "9091:9091"
        command: '/home/eclim/entrypoint.sh'
